# Use the official Node.js 18 LTS image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY ./src ./src

RUN ls

CMD ["npm", "run build"]

# Expose the port your application runs on (e.g., 3000)
EXPOSE 3000

# Start the application
CMD ["npm", "run start"]
