version: "3"

services:
  rabbitmq:
    image: rabbitmq:4
    container_name: rabbitmq
    ports:
      - "5672:5672"   # messaging
      - "15672:15672" # management UI 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # persistent data
  simrail-multiplayer:
    build:
      context: .
      dockerfile: connectors/simrail-multiplayer/Dockerfile
    container_name: simrail-multiplayer
    ports:
      - "3100:3100"
volumes:
  rabbitmq_data:
